/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author user
 */
public class EliminarEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarEmpleado
     */
    public EliminarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDespedir = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDNIEmpleadoEliminar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDespedir.setBackground(new java.awt.Color(153, 255, 204));
        pnlDespedir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("DNI del empleado");
        pnlDespedir.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        pnlDespedir.add(txtDNIEmpleadoEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, 50));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        pnlDespedir.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 170, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DESPEDIR");
        pnlDespedir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        getContentPane().add(pnlDespedir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlDespedir;
    private javax.swing.JTextField txtDNIEmpleadoEliminar;
    // End of variables declaration//GEN-END:variables
}
