/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author user
 */
public class frmAgregarEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarEmpleado
     */
    public frmAgregarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContrato = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtPrimerNombre = new javax.swing.JTextField();
        txtSegundoNombre = new javax.swing.JTextField();
        cbxPuesto = new javax.swing.JComboBox<>();
        cbxTurno = new javax.swing.JComboBox<>();
        btnRegistrarEmpleado = new javax.swing.JButton();
        btnAgregarCredencial = new javax.swing.JButton();
        txtApellidoPaterno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtNumeroDeTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContrato.setBackground(new java.awt.Color(0, 0, 0));
        pnlContrato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Puesto laboral");
        pnlContrato.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Turno");
        pnlContrato.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("AGREGAR EMPLEADO");
        pnlContrato.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Numero de Telefono");
        pnlContrato.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Segundo Nombre");
        pnlContrato.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Primer Nombre");
        pnlContrato.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        txtNombreEmpleado.setBackground(new java.awt.Color(204, 204, 204));
        pnlContrato.add(txtNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, 50));

        txtPrimerNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtPrimerNombre.addActionListener(this::txtPrimerNombreActionPerformed);
        pnlContrato.add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 230, 50));

        txtSegundoNombre.setBackground(new java.awt.Color(204, 204, 204));
        pnlContrato.add(txtSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 230, 50));

        cbxPuesto.setBackground(new java.awt.Color(204, 204, 204));
        cbxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlContrato.add(cbxPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 270, 50));

        cbxTurno.setBackground(new java.awt.Color(204, 204, 204));
        cbxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlContrato.add(cbxTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 270, 50));

        btnRegistrarEmpleado.setBackground(new java.awt.Color(204, 204, 204));
        btnRegistrarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarEmpleado.setText("Registrar empleado");
        pnlContrato.add(btnRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 230, 70));

        btnAgregarCredencial.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregarCredencial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregarCredencial.setText("Agregar credencial");
        btnAgregarCredencial.setEnabled(false);
        pnlContrato.add(btnAgregarCredencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 230, 70));

        txtApellidoPaterno.setBackground(new java.awt.Color(204, 204, 204));
        pnlContrato.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 230, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellido Paterno");
        pnlContrato.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Apellido Materno");
        pnlContrato.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        txtApellidoMaterno.setBackground(new java.awt.Color(204, 204, 204));
        pnlContrato.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 230, 50));

        txtNumeroDeTelefono.setBackground(new java.awt.Color(204, 204, 204));
        pnlContrato.add(txtNumeroDeTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 270, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DNI");
        pnlContrato.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        getContentPane().add(pnlContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarCredencial;
    public javax.swing.JButton btnRegistrarEmpleado;
    public javax.swing.JComboBox<String> cbxPuesto;
    public javax.swing.JComboBox<String> cbxTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel pnlContrato;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    public javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtNumeroDeTelefono;
    public javax.swing.JTextField txtPrimerNombre;
    public javax.swing.JTextField txtSegundoNombre;
    // End of variables declaration//GEN-END:variables
}
