/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author user
 */
public class frmAgregarEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarEmpleado
     */
    public frmAgregarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContrato = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtApellidoEmpleado = new javax.swing.JTextField();
        txtDNIEmpleado = new javax.swing.JTextField();
        cbxPuesto = new javax.swing.JComboBox<>();
        cbxTurno = new javax.swing.JComboBox<>();
        btnRegistrarEmpleado = new javax.swing.JButton();
        btnAgregarCredencial = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContrato.setBackground(new java.awt.Color(0, 0, 0));
        pnlContrato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Puesto laboral");
        pnlContrato.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Turno");
        pnlContrato.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("AGREGAR EMPLEADO");
        pnlContrato.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombres del empleado");
        pnlContrato.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DNI del empleado");
        pnlContrato.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellidos del empleado");
        pnlContrato.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txtNombreEmpleado.setBackground(new java.awt.Color(204, 204, 204));
        pnlContrato.add(txtNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 230, 50));

        txtApellidoEmpleado.setBackground(new java.awt.Color(204, 204, 204));
        txtApellidoEmpleado.addActionListener(this::txtApellidoEmpleadoActionPerformed);
        pnlContrato.add(txtApellidoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 230, 50));

        txtDNIEmpleado.setBackground(new java.awt.Color(204, 204, 204));
        pnlContrato.add(txtDNIEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 230, 50));

        cbxPuesto.setBackground(new java.awt.Color(204, 204, 204));
        cbxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlContrato.add(cbxPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 270, 50));

        cbxTurno.setBackground(new java.awt.Color(204, 204, 204));
        cbxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlContrato.add(cbxTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 270, 50));

        btnRegistrarEmpleado.setBackground(new java.awt.Color(204, 204, 204));
        btnRegistrarEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrarEmpleado.setText("Registrar empleado");
        pnlContrato.add(btnRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 230, 70));

        btnAgregarCredencial.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregarCredencial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregarCredencial.setText("Agregar credencial");
        btnAgregarCredencial.setEnabled(false);
        pnlContrato.add(btnAgregarCredencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 230, 70));

        getContentPane().add(pnlContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCredencial;
    private javax.swing.JButton btnRegistrarEmpleado;
    private javax.swing.JComboBox<String> cbxPuesto;
    private javax.swing.JComboBox<String> cbxTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnlContrato;
    private javax.swing.JTextField txtApellidoEmpleado;
    private javax.swing.JTextField txtDNIEmpleado;
    private javax.swing.JTextField txtNombreEmpleado;
    // End of variables declaration//GEN-END:variables
}
