/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author user
 */
public class frmCancelarCita extends javax.swing.JInternalFrame {

    /**
     * Creates new form CancelarCita
     */
    public frmCancelarCita() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCancelarCita = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdCita = new javax.swing.JTextField();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancelarCita = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCancelarCita.setBackground(new java.awt.Color(204, 0, 204));
        pnlCancelarCita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CANCELAR CITA");
        pnlCancelarCita.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        txtIdCita.setBackground(new java.awt.Color(255, 204, 255));
        pnlCancelarCita.add(txtIdCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 340, 50));

        cbxEstado.setBackground(new java.awt.Color(255, 204, 255));
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlCancelarCita.add(cbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 340, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Cita");
        pnlCancelarCita.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Estado");
        pnlCancelarCita.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        btnCancelarCita.setBackground(new java.awt.Color(255, 204, 255));
        btnCancelarCita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelarCita.setText("CANCELAR");
        pnlCancelarCita.add(btnCancelarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 340, 50));

        getContentPane().add(pnlCancelarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCita;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlCancelarCita;
    private javax.swing.JTextField txtIdCita;
    // End of variables declaration//GEN-END:variables
}
