/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author James
 */
public class frmMenusVeterinaria extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMenusVeterinaria.class.getName());

    /**
     * Creates new form MenusVeterinaria
     */
    public frmMenusVeterinaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        spnConetenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuClientes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuCitas = new javax.swing.JMenu();
        itemCancelar = new javax.swing.JMenuItem();
        itemAgenda = new javax.swing.JMenuItem();
        MenuAgendas = new javax.swing.JMenu();
        itemCitas = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenu();
        itemEstado = new javax.swing.JMenuItem();
        MenuEmpleados = new javax.swing.JMenu();
        itemAgregar = new javax.swing.JMenuItem();
        itemEliminar = new javax.swing.JMenuItem();
        itemTabla = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        spnConetenedor.setBackground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout spnConetenedorLayout = new javax.swing.GroupLayout(spnConetenedor);
        spnConetenedor.setLayout(spnConetenedorLayout);
        spnConetenedorLayout.setHorizontalGroup(
            spnConetenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
        );
        spnConetenedorLayout.setVerticalGroup(
            spnConetenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        MenuClientes.setText("Clientes");

        jMenuItem1.setText("Registrar Clientes");
        MenuClientes.add(jMenuItem1);

        jMenuBar1.add(MenuClientes);

        MenuCitas.setText("Citas");

        itemCancelar.setText("Cancelar Cita");
        MenuCitas.add(itemCancelar);

        itemAgenda.setText("Agenda De Citas");
        MenuCitas.add(itemAgenda);

        jMenuBar1.add(MenuCitas);

        MenuAgendas.setText("Agenda");

        itemCitas.setText("Citas Asignadas");
        MenuAgendas.add(itemCitas);

        jMenuBar1.add(MenuAgendas);

        Modificar.setText("Procesos");

        itemEstado.setText("Estado De La Cita");
        Modificar.add(itemEstado);

        jMenuBar1.add(Modificar);

        MenuEmpleados.setText("Empleados");

        itemAgregar.setText("Agregar empleados");
        MenuEmpleados.add(itemAgregar);

        itemEliminar.setText("Eliminar Empleado");
        MenuEmpleados.add(itemEliminar);

        itemTabla.setText("Tabla De Empleados");
        MenuEmpleados.add(itemTabla);

        jMenuBar1.add(MenuEmpleados);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnConetenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnConetenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMenusVeterinaria().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MenuAgendas;
    public javax.swing.JMenu MenuCitas;
    public javax.swing.JMenu MenuClientes;
    public javax.swing.JMenu MenuEmpleados;
    public javax.swing.JMenu Modificar;
    private javax.swing.JMenuItem itemAgenda;
    private javax.swing.JMenuItem itemAgregar;
    private javax.swing.JMenuItem itemCancelar;
    private javax.swing.JMenuItem itemCitas;
    private javax.swing.JMenuItem itemEliminar;
    private javax.swing.JMenuItem itemEstado;
    private javax.swing.JMenuItem itemTabla;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane spnConetenedor;
    // End of variables declaration//GEN-END:variables
}
