/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author user
 */
public class frmRegistrarClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarClientes
     */
    public frmRegistrarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistrodeClientes = new javax.swing.JPanel();
        btnRegistrarCliente = new javax.swing.JButton();
        btnAgregarMascota = new javax.swing.JButton();
        txtNombreClie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTelefonoClie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDniClie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDireccionClie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRegistrodeClientes.setBackground(new java.awt.Color(255, 255, 0));
        pnlRegistrodeClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarCliente.setBackground(new java.awt.Color(255, 153, 0));
        btnRegistrarCliente.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnRegistrarCliente.setText("Registrar Cliente");
        pnlRegistrodeClientes.add(btnRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 330, 70));

        btnAgregarMascota.setBackground(new java.awt.Color(255, 153, 0));
        btnAgregarMascota.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnAgregarMascota.setText("Agregar Mascota");
        btnAgregarMascota.setEnabled(false);
        btnAgregarMascota.addActionListener(this::btnAgregarMascotaActionPerformed);
        pnlRegistrodeClientes.add(btnAgregarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 330, 70));

        txtNombreClie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlRegistrodeClientes.add(txtNombreClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 330, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Nombre del Cliente");
        pnlRegistrodeClientes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 270, -1));

        txtTelefonoClie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlRegistrodeClientes.add(txtTelefonoClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 330, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Teléfono del Cliente");
        pnlRegistrodeClientes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 350, 30));

        txtDniClie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDniClie.addActionListener(this::txtDniClieActionPerformed);
        pnlRegistrodeClientes.add(txtDniClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 330, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DNI del Cliente");
        pnlRegistrodeClientes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 300, -1));

        txtDireccionClie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlRegistrodeClientes.add(txtDireccionClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 330, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Dirección del Cliente");
        pnlRegistrodeClientes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 360, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Registrar Clientes");
        pnlRegistrodeClientes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        getContentPane().add(pnlRegistrodeClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDniClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniClieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniClieActionPerformed

    private void btnAgregarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMascotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarMascota;
    public javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JPanel pnlRegistrodeClientes;
    public javax.swing.JTextField txtDireccionClie;
    public javax.swing.JTextField txtDniClie;
    public javax.swing.JTextField txtNombreClie;
    public javax.swing.JTextField txtTelefonoClie;
    // End of variables declaration//GEN-END:variables
}
